// ── The NEON CLASH roster: five fighters, five philosophies ─────────────────
import type { CharacterDef } from "./types";

export const ROSTER: CharacterDef[] = [
  // ══════════════════════════ KAI — the all-rounder ═════════════════════════
  {
    id: "kai",
    name: "FIGHTER",
    title: "The Vanguard",
    archetype: "All-Rounder",
    desc: "Clean fundamentals, honest buttons and a launcher that begs to be jump-cancelled. The FIGHTER teaches the game — and punishes anyone who hasn't learned it.",
    color: "#34d399", glow: "#6ee7b7", dark: "#052e21",
    scale: 1.0, girth: 1.0,
    walkF: 4.3, walkB: 3.4, dashSpeed: 13, dashDur: 12,
    jumpVel: 17.5, gravity: 0.85, maxFall: 15, jumps: 1,
    weight: 1.0, hp: 120, bodyW: 56, bodyH: 150,
    acc: "headband", superName: "DRAGON RUSH",
    pokes: [1, 3, 4], antiAir: 2, keepaway: [5],
    comboChart: { 1: [1, 2, 3, 4], 2: [1, 3], 3: [], 4: [], 5: [2], 6: [] },
    preferredRange: 130,
    moves: [
      { slot: 1, id: "kai_jab", name: "Straight Jab", kind: "strike", anim: "jab", sfx: "swing", hitSfx: "hit",
        startup: 6, active: 4, recovery: 11, damage: 5, hitstun: 16, blockstun: 10,
        range: 78, h: 42, yOff: 104, kb: { x: 2.5, y: 0 }, guard: "mid",
        airOk: true, chains: [1, 2, 3, 4],
        desc: "Blink-fast poke. Chains into itself and everything else." },
      { slot: 2, id: "kai_palm", name: "Rising Gale Palm", kind: "strike", anim: "upper", sfx: "swingHeavy", hitSfx: "hitAir",
        startup: 14, active: 6, recovery: 26, damage: 12, hitstun: 42, blockstun: 16,
        range: 66, h: 78, yOff: 118, kb: { x: 3, y: -13.5 }, guard: "mid",
        jumpCancel: true,
        desc: "Launcher. On hit, cancel straight into a jump and chase them up." },
      { slot: 3, id: "kai_heel", name: "Heaven Heel", kind: "strike", anim: "heel", sfx: "swingHeavy", hitSfx: "hitBig",
        startup: 17, active: 5, recovery: 30, damage: 14, hitstun: 30, blockstun: 18,
        range: 96, h: 72, yOff: 112, kb: { x: 10, y: -4 }, guard: "mid",
        airOk: true,
        desc: "Big roundhouse finisher. Sends them flying — huge near the corner." },
      { slot: 4, id: "kai_sweep", name: "Iron Sweep", kind: "strike", anim: "sweep", sfx: "swing", hitSfx: "hit",
        startup: 15, active: 5, recovery: 24, damage: 9, hitstun: 26, blockstun: 12,
        range: 98, h: 28, yOff: 16, kb: { x: 6, y: -3 }, guard: "low",
        desc: "Low shin-kick that knocks down. Beats stand-blocking. Must be crouched against." },
      { slot: 5, id: "kai_palmshot", name: "Force Palm", kind: "projectile", anim: "shoot", sfx: "zap",
        startup: 13, active: 2, recovery: 20, damage: 8, hitstun: 20, blockstun: 11,
        range: 60, h: 60, yOff: 100, kb: { x: 5, y: -1 }, guard: "mid",
        projectile: { speed: 9.5, radius: 15, level: 1, life: 130, color: "#34d399" },
        desc: "A honest green fireball. Controls the middle of the screen." },
      { slot: 6, id: "kai_super", name: "Dragon Rush", kind: "strike", anim: "barrage", sfx: "super", hitSfx: "hitBig",
        startup: 12, active: 24, recovery: 30, damage: 5, hits: 6, hitstun: 30, blockstun: 14,
        range: 92, h: 120, yOff: 92, kb: { x: 9, y: -6 }, guard: "mid",
        cost: 100, invuln: 12, selfVx: 6.5, wallSlam: false,
        desc: "SUPER · 100 meter. An invincible six-hit stampede across the screen." },
    ],
  },

  // ════════════════════ VOLT — the velocity user ════════════════════════════
  {
    id: "volt",
    name: "VELOCITY",
    title: "Lightspeed Menace",
    archetype: "Velocity / Rushdown",
    desc: "The fastest thing on the stage. Triple jabs, a teleport, an air dash and a knee that starts pain. Its damage is low — its tempo is lethal.",
    color: "#fbbf24", glow: "#fde68a", dark: "#3a2703",
    scale: 0.96, girth: 0.92,
    walkF: 5.2, walkB: 4.2, dashSpeed: 16.5, dashDur: 11,
    jumpVel: 17, gravity: 0.9, maxFall: 15, jumps: 1,
    airDash: true, weight: 1.05, hp: 120, bodyW: 52, bodyH: 144,
    acc: "goggles", superName: "OVERDRIVE",
    pokes: [1, 4, 2], antiAir: 3, keepaway: [],
    comboChart: { 1: [1, 2, 3, 4], 3: [1, 2], 2: [], 4: [1, 2, 3], 5: [1], 6: [] },
    preferredRange: 90,
    moves: [
      { slot: 1, id: "volt_jab", name: "Static Jab", kind: "strike", anim: "jab", sfx: "swing", hitSfx: "hit",
        startup: 4, active: 3, recovery: 9, damage: 3, hitstun: 14, blockstun: 9,
        range: 64, h: 38, yOff: 100, kb: { x: 2, y: 0 }, guard: "mid",
        airOk: true, chains: [1, 2, 3, 4],
        desc: "The fastest jab in the game (4f). Stuffs everything, chains x3." },
      { slot: 2, id: "volt_rush", name: "Volt Rush", kind: "strike", anim: "rush", sfx: "dash", hitSfx: "hit",
        startup: 9, active: 12, recovery: 24, damage: 3, hits: 3, hitstun: 18, blockstun: 10,
        range: 74, h: 64, yOff: 96, kb: { x: 6, y: -2 }, guard: "mid",
        selfVx: 10.5,
        desc: "Blitz forward with three lightning strikes. Very unsafe if blocked." },
      { slot: 3, id: "volt_knee", name: "Thunder Knee", kind: "strike", anim: "knee", sfx: "swingHeavy", hitSfx: "hitAir",
        startup: 8, active: 5, recovery: 22, damage: 8, hitstun: 40, blockstun: 14,
        range: 58, h: 66, yOff: 90, kb: { x: 2.5, y: -12.5 }, guard: "mid",
        airOk: true, jumpCancel: true,
        desc: "8-frame launching knee. The whole gameplan starts here." },
      { slot: 4, id: "volt_palm", name: "Flash Palm", kind: "strike", anim: "push", sfx: "push", hitSfx: "hit",
        startup: 12, active: 4, recovery: 19, damage: 6, hitstun: 28, blockstun: 16,
        range: 62, h: 52, yOff: 104, kb: { x: 7, y: 0 }, guard: "mid",
        chains: [1, 3],
        desc: "Stunning palm slap — massive frame advantage. Reset the pressure." },
      { slot: 5, id: "volt_blink", name: "Blink Step", kind: "special", anim: "blink", sfx: "blink",
        startup: 3, active: 8, recovery: 14, damage: 0, hitstun: 0, blockstun: 0,
        range: 0, h: 0, yOff: 0, kb: { x: 0, y: 0 }, guard: "mid",
        teleport: 176, invuln: 8, cooldown: 40,
        desc: "Teleport 180px forward, intangible mid-blink. Cross them up." },
      { slot: 6, id: "volt_super", name: "Overdrive", kind: "strike", anim: "barrage", sfx: "super", hitSfx: "hitBig",
        startup: 8, active: 26, recovery: 28, damage: 2.6, hits: 12, hitstun: 26, blockstun: 12,
        range: 100, h: 130, yOff: 96, kb: { x: 10, y: -7 }, guard: "mid",
        cost: 100, invuln: 14,
        desc: "SUPER · 100 meter. Twelve hits of pure electricity, invincible start." },
    ],
  },

  // ════════════════════ JETT — the air comboer ══════════════════════════════
  {
    id: "jett",
    name: "AIR",
    title: "Sky Dancer",
    archetype: "Air Comboer",
    desc: "Double jump, feather fall, a divekick that loops. Its ground game is thin — so it simply never touches the ground. Highest execution, highest ceiling.",
    color: "#38bdf8", glow: "#7dd3fc", dark: "#082f49",
    scale: 1.0, girth: 0.94,
    walkF: 4.4, walkB: 3.6, dashSpeed: 13.5, dashDur: 11,
    jumpVel: 18.5, gravity: 0.72, maxFall: 11, jumps: 2,
    weight: 0.95, hp: 120, bodyW: 52, bodyH: 148,
    acc: "scarf", superName: "TEMPEST WALTZ",
    pokes: [1, 3, 2], antiAir: 2, keepaway: [5],
    comboChart: { 1: [2, 3], 2: [1, 3, 4], 3: [4, 1], 4: [1, 3, 4], 5: [], 6: [] },
    preferredRange: 150,
    moves: [
      { slot: 1, id: "jett_slash", name: "Talon Slash", kind: "strike", anim: "talon", sfx: "swing", hitSfx: "hit",
        startup: 7, active: 5, recovery: 14, damage: 5, hitstun: 17, blockstun: 10,
        range: 76, h: 48, yOff: 108, kb: { x: 3, y: -1 }, guard: "mid",
        airOk: true, chains: [2, 3],
        desc: "Aerial claw swipe. Startup stays fast in the air — her combo glue." },
      { slot: 2, id: "jett_upper", name: "Sky Upper", kind: "strike", anim: "upper", sfx: "swingHeavy", hitSfx: "hitAir",
        startup: 12, active: 6, recovery: 26, damage: 11, hitstun: 44, blockstun: 15,
        range: 62, h: 84, yOff: 122, kb: { x: 2.5, y: -14 }, guard: "mid",
        jumpCancel: true,
        desc: "Soaring launcher. Jump-cancel it — the dance begins." },
      { slot: 3, id: "jett_spin", name: "Cyclone Kick", kind: "strike", anim: "spin", sfx: "swingHeavy", hitSfx: "hitBig",
        startup: 15, active: 8, recovery: 26, damage: 6, hits: 2, hitstun: 26, blockstun: 15,
        range: 88, h: 80, yOff: 96, kb: { x: 9, y: -4 }, guard: "mid",
        airOk: true,
        desc: "Two-hit pirouette. In the air it briefly holds her float." },
      { slot: 4, id: "jett_dive", name: "Dive Talon", kind: "strike", anim: "dive", sfx: "whiff", hitSfx: "hitAir",
        startup: 7, active: 40, recovery: 10, damage: 10, hitstun: 34, blockstun: 14,
        range: 60, h: 90, yOff: 30, kb: { x: 3, y: -7 }, guard: "mid",
        airOnly: true, diveKick: true, popUpOnHit: true, chains: [1, 3, 4],
        desc: "AIR ONLY. Spear down diagonally — on hit she rebounds, ready to loop." },
      { slot: 5, id: "jett_gust", name: "Gust Cutter", kind: "projectile", anim: "shoot", sfx: "zap",
        startup: 12, active: 2, recovery: 18, damage: 7, hitstun: 18, blockstun: 10,
        range: 60, h: 50, yOff: 100, kb: { x: 4, y: -1 }, guard: "mid",
        airOk: true,
        projectile: { speed: 10, vy: 0, radius: 12, level: 1, life: 120, color: "#38bdf8" },
        desc: "Crescent of compressed air. Angles downward when fired mid-flight." },
      { slot: 6, id: "jett_super", name: "Tempest Waltz", kind: "strike", anim: "barrage", sfx: "super", hitSfx: "hitBig",
        startup: 9, active: 28, recovery: 30, damage: 3, hits: 8, hitstun: 30, blockstun: 14,
        range: 112, h: 140, yOff: 100, kb: { x: 12, y: -8 }, guard: "mid",
        cost: 100, invuln: 12, airOk: true,
        desc: "SUPER · 100 meter. An eight-hit hurricane around her, ground or air." },
    ],
  },

  // ════════════════════ SAGE — the zoner ════════════════════════════════════
  {
    id: "sage",
    name: "ZONER",
    title: "The Tempest Seer",
    archetype: "Zoner",
    desc: "Slow feet, infinite reach. Arc bolts, a proximity orb, an anti-air lance and a gust that throws you back to full screen. Getting in means earning it.",
    color: "#c084fc", glow: "#d8b4fe", dark: "#2e1065",
    scale: 1.02, girth: 0.96,
    walkF: 3.5, walkB: 3.0, dashSpeed: 12, dashDur: 10,
    jumpVel: 16, gravity: 0.9, maxFall: 15, jumps: 1,
    weight: 1.0, hp: 120, bodyW: 54, bodyH: 152,
    acc: "hat", superName: "ANNIHILATION SPHERE",
    pokes: [1, 4], antiAir: 5, keepaway: [1, 2, 3, 5],
    comboChart: { 1: [2], 4: [1, 3], 3: [], 2: [], 5: [1], 6: [] },
    preferredRange: 520,
    moves: [
      { slot: 1, id: "sage_bolt", name: "Arc Bolt", kind: "projectile", anim: "shoot", sfx: "zap",
        startup: 12, active: 2, recovery: 18, damage: 8, hitstun: 20, blockstun: 11,
        range: 60, h: 60, yOff: 104, kb: { x: 5, y: -1 }, guard: "mid",
        airOk: true,
        projectile: { speed: 11, radius: 14, level: 1, life: 140, color: "#c084fc" },
        desc: "Fast violet bolt. The wall that walks forward." },
      { slot: 2, id: "sage_heavy", name: "Thunder Arc", kind: "projectile", anim: "shootWide", sfx: "zapBig",
        startup: 19, active: 2, recovery: 26, damage: 12, hitstun: 24, blockstun: 14,
        range: 60, h: 80, yOff: 104, kb: { x: 8, y: -3 }, guard: "mid",
        projectile: { speed: 8, radius: 22, level: 2, life: 150, color: "#a855f7" },
        desc: "Heavy orb of storm — eats lesser projectiles whole." },
      { slot: 3, id: "sage_orb", name: "Orb Ward", kind: "projectile", anim: "orbCast", sfx: "orb",
        startup: 20, active: 2, recovery: 22, damage: 10, hitstun: 30, blockstun: 14,
        range: 0, h: 0, yOff: 0, kb: { x: 4, y: -7 }, guard: "mid",
        orb: true, cooldown: 60,
        desc: "Plants a sentry orb ahead. It detonates automatically when they enter its range." },
      { slot: 4, id: "sage_push", name: "Gale Rebuke", kind: "strike", anim: "push", sfx: "push", hitSfx: "hit",
        startup: 10, active: 6, recovery: 20, damage: 5, hitstun: 22, blockstun: 16,
        range: 96, h: 98, yOff: 92, kb: { x: 16, y: -2 }, guard: "mid",
        chains: [1, 3],
        desc: "A wall of wind that hurls them back to zoning range. The get-off-me button." },
      { slot: 5, id: "sage_lance", name: "Sky Lance", kind: "projectile", anim: "lance", sfx: "zap",
        startup: 14, active: 2, recovery: 20, damage: 9, hitstun: 26, blockstun: 12,
        range: 80, h: 90, yOff: 130, kb: { x: 3, y: -6 }, guard: "mid",
        projectile: { speed: 7.7, vy: -9.2, gravity: 0.18, radius: 13, level: 1, life: 150, color: "#e9d5ff" },
        desc: "Anti-air comet fired at 50°. Jump at the ZONER and meet this." },
      { slot: 6, id: "sage_super", name: "Annihilation Sphere", kind: "projectile", anim: "sphereCast", sfx: "super", hitSfx: "hitBig",
        startup: 16, active: 2, recovery: 34, damage: 5, hitstun: 26, blockstun: 16,
        range: 0, h: 0, yOff: 0, kb: { x: 5, y: -4 }, guard: "mid",
        cost: 100, invuln: 10,
        projectile: { speed: 3.6, radius: 42, level: 3, life: 320, color: "#7c3aed", multiHit: true, hitCooldown: 10 },
        desc: "SUPER · 100 meter. A slow, devouring sphere that shoves them down the stage, hit after hit." },
    ],
  },

  // ════════════════════ BRUNO — the grappler ════════════════════════════════
  {
    id: "bruno",
    name: "GRAPPLER",
    title: "The Mountain",
    archetype: "Heavy Grappler",
    desc: "Slow as erosion, hits like a landslide. Armored charges, overhead slams that crack the floor, and a command grab that erases a third of your life.",
    color: "#fb923c", glow: "#fdba74", dark: "#431407",
    scale: 1.14, girth: 1.22,
    walkF: 3.2, walkB: 2.6, dashSpeed: 11, dashDur: 12,
    jumpVel: 15, gravity: 1.0, maxFall: 16, jumps: 1,
    weight: 0.8, hp: 120, bodyW: 70, bodyH: 162,
    acc: "mohawk", superName: "COLOSSUS GRIP",
    pokes: [1, 4, 5], antiAir: 2, keepaway: [5],
    comboChart: { 1: [5, 4], 2: [3, 4], 3: [], 4: [3], 5: [1], 6: [] },
    preferredRange: 110,
    moves: [
      { slot: 1, id: "bruno_hammer", name: "Hammer Fist", kind: "strike", anim: "jab", sfx: "swingHeavy", hitSfx: "hit",
        startup: 11, active: 5, recovery: 18, damage: 9, hitstun: 20, blockstun: 12,
        range: 98, h: 48, yOff: 100, kb: { x: 5, y: -1 }, guard: "mid",
        airOk: true, chains: [5, 4],
        desc: "A telephone pole of a straight punch. Deceptively long." },
      { slot: 2, id: "bruno_launch", name: "Mountain Riser", kind: "strike", anim: "upper", sfx: "swingHeavy", hitSfx: "hitAir",
        startup: 17, active: 6, recovery: 28, damage: 13, hitstun: 42, blockstun: 16,
        range: 74, h: 86, yOff: 120, kb: { x: 3, y: -13 }, guard: "overhead",
        jumpCancel: true,
        desc: "OVERHEAD launcher. Catches crouch-blockers and starts juggles." },
      { slot: 3, id: "bruno_slam", name: "Seismic Slam", kind: "strike", anim: "slam", sfx: "quake", hitSfx: "hitBig",
        startup: 21, active: 6, recovery: 30, damage: 17, hitstun: 34, blockstun: 18,
        range: 92, h: 116, yOff: 84, kb: { x: 9, y: -9 }, guard: "overhead",
        wallSlam: true,
        desc: "OVERHEAD. Both fists into the earth. Wall-slams them into the corner and back." },
      { slot: 4, id: "bruno_charge", name: "Bull Charge", kind: "strike", anim: "charge", sfx: "dash", hitSfx: "hitBig",
        startup: 16, active: 14, recovery: 26, damage: 12, hitstun: 28, blockstun: 16,
        range: 82, h: 96, yOff: 92, kb: { x: 12, y: -4 }, guard: "mid",
        selfVx: 7.5, armor: 1,
        desc: "Armored freight train. Absorbs one hit and keeps trucking." },
      { slot: 5, id: "bruno_quake", name: "Ground Quake", kind: "projectile", anim: "stomp", sfx: "quake",
        startup: 18, active: 2, recovery: 26, damage: 10, hitstun: 30, blockstun: 14,
        range: 0, h: 0, yOff: 0, kb: { x: 6, y: -6 }, guard: "low",
        projectile: { speed: 7, radius: 20, level: 1, life: 160, color: "#fb923c", low: true, w: 52, h: 36 },
        desc: "LOW shockwave that crawls the floor. Stand-blocking won't save you." },
      { slot: 6, id: "bruno_super", name: "Colossus Grip", kind: "grab", anim: "grab", sfx: "grab", hitSfx: "hitBig",
        startup: 13, active: 5, recovery: 34, damage: 30, hitstun: 40, blockstun: 0,
        range: 82, h: 150, yOff: 80, kb: { x: 14, y: -7 }, guard: "unblockable",
        cost: 100, armor: 1, wallSlam: true,
        desc: "SUPER · 100 meter. An unblockable command grab slammed into the stage wall." },
    ],
  },
];

export const getChar = (id: string): CharacterDef =>
  ROSTER.find((c) => c.id === id) ?? ROSTER[0];

export const DIFFICULTY_INFO: Record<string, { label: string; blurb: string; color: string }> = {
  easy: {
    label: "EASY",
    blurb: "A learning dummy. Slow reads, rarely blocks, drops everything. For absolute first-timers.",
    color: "#34d399",
  },
  medium: {
    label: "MEDIUM",
    blurb: "Real fundamentals. Blocks, anti-airs and short punishes. Beats most casuals.",
    color: "#38bdf8",
  },
  hard: {
    label: "HARD",
    blurb: "Sharp reactions, launcher combos, frame-trap pressure. Veterans and prodigies only.",
    color: "#fbbf24",
  },
  extreme: {
    label: "EXTREME",
    blurb: "A frame-perfect tyrant. Optimal punishes, reads your habits, baits your buttons. Good luck.",
    color: "#fb7185",
  },
};
